export const logos = [
    { src: '/assets/Logos/js.png', alt: 'JavaScript Logo', delay: 150},
    { src: '/assets/Logos/icons8-python-96.png', alt: 'Python Logo', delay: 150},
    { src: '/assets/Logos/icons8-tailwind-css-96.png', alt: 'Tailwind CSS Logo', delay: 150},
    { src: '/assets/Logos/postman-icon.png', alt: 'Postman API Logo', delay: 150},
    { src: '/assets/Logos/icons8-html-logo-96.png', alt: 'HTML Logo', delay: 150},
    { src: '/assets/Logos/icons8-css-logo-96.png', alt: 'CSS Logo', delay: 150},
    { src: '/assets/Logos/icons8-node-js-96.png', alt: 'Node JS Logo', delay: 150},
    { src: '/assets/Logos/icons8-react-native-96.png', alt: 'React Native Logo', delay: 300},
    { src: '/assets/Logos/icons8-figma-96.png', alt: 'Figma Logo', delay: 300},
    { src: '/assets/Logos/icons8-visual-studio-96.png', alt: 'Visual Studio Code Logo', delay: 300},
    { src: '/assets/Logos/icons8-ejs-96.png', alt: 'EJS Logo', delay: 300},
    { src: '/assets/Logos/icons8-django-100.png', alt: 'Django Logo', delay: 300},
    { src: '/assets/Logos/icons8-postgresql-96.png', alt: 'PostgreSQL Logo', delay: 300},
    { src: '/assets/Logos/icons8-c-96.png', alt:'C Logo', delay: 300},
    { src: '/assets/Logos/icons8-flask-96.png', alt:'Flask Logo', delay: 500},
    { src: '/assets/Logos/icons8-mysql-96.png', alt:'MySQL Logo', delay: 500},
    { src: '/vite.svg', alt: 'Vite Logo', delay: 500},
]